### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Hanakus0** [Hanakus0/graduation_project#17]

**Comment by Hanakus0** [comment]
■Webアプリの概要
このWebアプリは、「本気ではない」アイデアを投稿・評価し合い、アイデアの質向上を手助けするサイトです。年齢・性別を問わず、アプリ開発のアイデアに困っている人や新しい視点を求める方を対象としています。従来のSNSやブログと異なり、アプリのアイデアに特化した投稿を募ることで、ネタ探しの手間を解消します。没になりそうな質の低いアイデアも歓迎し、気軽に評価・参考にできる点が特徴です。用途とジャンルでの検索機能や無作為ランダム表示欄を設けることで多様なアイデアへのアクセスを容易にします。スタンプ、コメント、フォロー機能などを通じて、ユーザー間の交流とフィードバックを促進し、コミュニティ感を培っていきます。これにより、労力をかけずに新しい視点のアイデアを閲覧・精査でき、生成AIでは生み出しにくい「外れ値」的なアイデアも期待できます。互いに刺激し合いながら、アイデアの質を向上させる機会を提供する、ユニークなプラットフォームです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

■MVPリリースまで
- [ ] ユーザー登録機能 (Googleログイン)
- [ ] パスワードリセット
- [ ] ログイン機能
- [ ] 投稿関連機能 (基本的なCRUD、画像添付)
- [ ] 他投稿の引用投稿
- [ ] 投稿下書き保存機能
- [ ] コメント関連機能 (基本的なCRUD)
- [ ] タグ関連機能 (基本的なCRUD)
- [ ] いいね・いいね解除機能 (投稿、コメント)
- [ ] ブックマーク
- [ ] ユーザー同士のフォロー
- [ ] キーワード検索
- [ ] タグ検索 (オートコンプリート)
- [ ] 投稿ランダム表示欄
- [ ] スタンプ数でのランキング表示欄
- [ ] コメント数でのランキング表示欄
- [ ] Twitter共有

■MVP後
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワード更新
- [ ] RSpec
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] OGP

■MVPレビュー依頼予定日
予定日：2024年 11月 X日

**Comment by ippei-shimizu** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- [パスワードリセット機能の調査](https://github.com/users/Hanakus0/projects/6?pane=issue&itemId=82894317)
- [パスワードリセット機能の実装](https://github.com/users/Hanakus0/projects/6?pane=issue&itemId=82894327)
